application: yetanothertwitterclient
version: 1
runtime: python
api_version: 1

handlers:
- url: /api.js
  secure: always
  static_files: api.js
  upload: api.js

- url: /.*
  secure: always
  script: main.py
  login: required


